config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'users#index'

  resources :users
  resources :organizations
  resources :donations
  resources :subscriptions

end

app/models/donation.rb
class Donation < ActiveRecord::Base

  belongs_to :user
  belongs_to :organization



end

app/models/organization.rb
class Organization < ActiveRecord::Base

  has_many :donations
  has_many :subscriptions

end

app/models/subscription.rb
class Subscription < ActiveRecord::Base

  belongs_to :organization
  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :donations
  has_many :subscriptions

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController

  skip_before_filter :verify_authenticity_token, only:[:create]

  def index
  end

  def new

  end

  def create
    # Set your secret key: remember to change this to your live secret key in production
    # See your keys here https://dashboard.stripe.com/account
    Stripe.api_key = "sk_test_mMnywRqDwhwDCL5813aYCOZd"

    # Get the credit card details submitted by the form
    token = params[:stripeToken]

    # Create the charge on Stripe's servers - this will charge the user's card
    begin
      charge = Stripe::Charge.create(
        :amount => 1000, # amount in cents, again
        :currency => "usd",
        :card => token,
        :description => "payinguser@example.com"
      )
      flash[:notice] = "Payment accepted."
      redirect_to users_path
    rescue Stripe::CardError => e
      # The card has been declined
      flash[:alert] = "Payment declined."
      render 'new'
    end
  end

  private
  def donation_params
    params.require(:donation).permit(:stripeToken,:amount, :currency, :card, :description)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end

  def new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/donations/new.html.erb
<script type="text/javascript" src="https://js.stripe.com/v2/"></script>

<script type="text/javascript">
  // This identifies your website in the createToken call below
  Stripe.setPublishableKey('pk_test_M9A0rrQ7ftsPdWuqqJxB6g5U');
  // ...
</script>

<form action="/donations" method="POST" id="payment-form">
  <span class="payment-errors"></span>

  <div class="form-row">
    <label>
      <span>Card Number</span>
      <input type="text" size="20" data-stripe="number"/>
    </label>
  </div>

  <div class="form-row">
    <label>
      <span>CVC</span>
      <input type="text" size="4" data-stripe="cvc"/>
    </label>
  </div>

  <div class="form-row">
    <label>
      <span>Expiration (MM/YYYY)</span>
      <input type="text" size="2" data-stripe="exp-month"/>
    </label>
    <span> / </span>
    <input type="text" size="4" data-stripe="exp-year"/>
  </div>

  <button type="submit">Submit Payment</button>
</form>
<script>
jQuery(function($) {
  $('#payment-form').submit(function(event) {
    var $form = $(this);

    // Disable the submit button to prevent repeated clicks
    $form.find('button').prop('disabled', true);

    Stripe.card.createToken($form, stripeResponseHandler);

    // Prevent the form from submitting with the default action
    return false;
  });
});


function stripeResponseHandler(status, response) {
  var $form = $('#payment-form');

  if (response.error) {
    // Show the errors on the form
    $form.find('.payment-errors').text(response.error.message);
    $form.find('button').prop('disabled', false);
  } else {
    // response contains id and card, which contains additional card details
    var token = response.id;

    // Insert the token into the form so it gets submitted to the server
    $form.append($('<input type="hidden" name="stripeToken" />').val(token));
    // and submit
    $form.get(0).submit();
  }
};
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nonprofit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="container">
  <div id="user_nav">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path %> |
      <%= link_to "Login", new_user_session_path %>
    <% end %>
  </div>


<%= flash[:alert] %>
<%= flash[:notice] %>


<%= yield %>

</body>
</html>

app/views/users/index.html.erb
<div id = "intro">
  <h1>Welcome to Non[Shall]Profit! - Your nonprofit wizard!</h1>
  <h3>What it is:<h3>
  <h5>A dasboard for nonprofit donations.  From here you can make donations and add subscriptions.</h5>
</div>

<br>
<%= link_to "Donate", new_donation_path, :class=> "btn btn-success", id: "donate" %>
</br>